### ISSUE TITLE
Converted CO2SYs to python

### ISSUE THREAD

**Issue by brorfred** [pyoceans/pyCO2#6]
Hi Filipe,

I've just converted most of CO2SYS to python from matlab. Would you be interested in adding the conversion here?

**Comment by ocefpaf** [comment]
Sure. That was the goal of this project, but I never got the time to do it.  Are you OK with GitHub and PRs?

**Comment by brorfred** [comment]
Yep!

Do you have a preferred API structure? Currently I’ve divided the project into two modules, one with all functions to calculate constants and one with a class to calculate the carbonate system. You use it by creating an instance as follows:

co = co2sys.calculations.CarbonateSystem(salt=35,temp=25,pres=1000,pCO2=600,pH=8)

all values are accessible in the resulting instance.

/B

**Comment by ocefpaf** [comment]
Looks good to me. Maybe I would just drop `1-level`

`co2sys.CarbonateSystem(salt=35,temp=25,pres=1000,pCO2=600,pH=8)`

 to reduced the verbosity, but that can be done later.

**Comment by brorfred** [comment]
OK, I changed it to 

import co2sys
co = co2sys.calc_co2_system(35,20,pH=8,pCO2=400)

The code is pushed to https://github.com/brorfred/pyCO2 

I need to turn on other K1/K2 methods than Millero 2010, clean up the code a bit, move references around, and write the documentation. Will do a pull request after that.

/B

**Comment by ocefpaf** [comment]
Thanks @brorfred! That looks awesome. I will do some boilerplate once your PR is here to prepare it for packaging. I want to ping @emiliom and @juoceano here who are interested in seeing this package out in the wild.

**Comment by emiliom** [comment]
Fantastic, @brorfred! 

FYI, a few months ago @ocefpaf and I [worked on](https://github.com/ocefpaf/mocsy/tree/python_package) improving the [Python wrapper for mocsy](https://github.com/jamesorr/mocsy), another carbonate system package.

**Comment by emiliom** [comment]
I'm using this existing issue to update and hopefully link up efforts.

@jamesorr mentioned to me this week that a group in New Zealand has converted CO2SYS to Python. Jim, could you give us a link to that effort, if one exists? I Googled for it and didn't find anything.

@brorfred, based on your Princeton affiliation (per your github profile), I'm assuming your own conversion effort is independent. If that's the case, maybe we can help unify and promote efforts.

**Comment by oscarbranson** [comment]
Hi Folks,

I've just written a [Python module for calculating seawater C and B speciation and B isotopes](https://github.com/oscarbranson/cbsyst).

A lot of it is CO2SYS inspired, and it uses the same zero-finding algorithms for C speciation.

It uses Mathis Hain's MyAMI model to adjust Ks for [Mg] and [Ca], so might be of particular interest to the palaeo-community.

In testing, it gives identical (to within error) results to CO2SYS analysis of the GLODAPv2 bottle data.

I started doing this earlier this year when this project seemed dormant... hopefully we haven't just duplicated our efforts!

Any thoughts/comments welcome!

**Comment by ocefpaf** [comment]
> In retrospect, this might be a bit of a duplication of effort..

I believe it is worth it. Thanks for letting us know.

BTW this project here is stuck mostly due to lack of free time to work on time. I guess that it will never get written unless there is some funding source for it.

**Comment by oscarbranson** [comment]
I know the feeling... Perhaps if we all coordinated our efforts into one module, we might produce something useful?

**Comment by ocefpaf** [comment]
> I know the feeling... Perhaps if we all coordinated our efforts into one module, we might produce something useful?

:+1: 

I should probably close this to avoid attracting people to this repo. I will check with others in order to that that. (I cannot promise, but I'll take a look at your project and see if I can contribute with something.)

**Comment by emiliom** [comment]
That looks like a great effort, @oscarbranson! Thanks for letting us know. I wish I had more time myself in the near future to contribute something, but I don't ...

> I should probably close this to avoid attracting people to this repo.

That makes sense. On the other hand, this empty repo has served nicely as a meeting point for people interested in carbonate-system code in Python!

**Comment by ocefpaf** [comment]
By closing the repo I mean remove code, lock the issues/PRs, and add a link in the README to guide people to the preferred version. I would not remove it entirely.

**Comment by oscarbranson** [comment]
True - this is high up the google search list. One of the first things I found when starting to look into this. I leave closing the repository to your discretion.

*IF* any of you are interested / have time to contribute to [cbsyst](https://github.com/oscarbranson/cbsyst), that'd be awesome. I'm putting together a [TODO.rst](https://github.com/oscarbranson/cbsyst/blob/master/TODO.md) of bite-sized (byte-sized?!) tasks that can usefully be done. If not, no worries - I'll forge ahead in my spare time!

As an incentive, I was thinking of putting a quick methods paper once it's a bit more complete - any contributions would obv be recognised with authorship/acknowledgement (depending on scale of contribution).

**Comment by emiliom** [comment]
@oscarbranson, I'd be interested in being pinged again around August, about contributing.

**Comment by pearseb** [comment]
@oscarbranson I'd also be interested in helping out. Although I'm not active on my github account, I've had a fair introduction to carbon chemistry by coding it into a global ocean biogeochemical model. And I've got python skills, although I've never created my own packages.

If you need someone to help out with those "byte"-sized tasks, then give me a shout.

**Comment by oscarbranson** [comment]
Fabulous, @emiliom and @pearseb. I'll be in touch.

Very little github / module knowledge required - I can help with that. Just python literacy! You can probably point out all the things I've done wrong in my code 😃 !

For the moment, I ditched the TODO list in favour of just using issues. If you ever find yourself wanting to do some useful python, take a look at the Issues list to find out what needs doing.

Going to stop commenting on here now, and ping you both on live issues.

**Comment by ocefpaf** [comment]
@oscarbranson I just updated to README, see https://github.com/pyoceans/pyCO2/blob/master/README.rst

I will add a `.github` with the same message for both new issues and PRs soon.

Thanks for you efforts on `cbsyst`. If I can some free time I can definitely help with some boilerplate stuff like testing, auto docs publishing, etc.

**Comment by oscarbranson** [comment]
Thanks @ocefpaf. It would be great to have you on board. I'm fairly new to writing Python modules and everything it entails, so any tips/suggestions would be very welcome.
